version: '3'

services: 

    django:
        build: ./backend
        restart: always
        command: >
            /bin/bash -c "pip install -r requirements.txt
            && python manage.py runserver 0.0.0.0:8000"
        volumes: 
            - ./backend:/app
        ports:
            - ${PORT}:8000

    mysql:
        image: mysql:5.7
        environment: 
            MYSQL_DATABASE: ${DATABASE_DBNAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        expose:
            - 3306
        volumes: 
            - channels-django-db:/var/lib/mysql

    pma:
        image: phpmyadmin/phpmyadmin
        environment: 
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - ${PMA_PORT}:80

    redis:
        image: redis:5
        ports:
            - 6379:6379

volumes: 
    channels-django-db: